export const BATALKAN_PESANAN_USER = 'BATALKAN_PESANAN_USER';
export const BATALKAN_PESANAN_USER_FAIL = 'BATALKAN_PESANAN_USER_FAIL';
export const BATALKAN_PESANAN_USER_SUCCESS = 'BATALKAN_PESANAN_USER_SUCCESS';


export const GOTO_HOME = 'GOTO_HOME';
